"use client";

// VOICE key → filename map. Keys match voices.json, filenames match generated MP3s.
export const VOICE = {
  welcome: "welcome.mp3",
  menuTitle: "menu_title.mp3",
  menuSubtitle: "menu_subtitle.mp3",
  menuParts: "menu_parts.mp3",
  menuCompleted: "menu_completed.mp3",
  menuMissionComplete: "menu_mission_complete.mp3",
  partCalc: "part_calc.mp3",
  partSensors: "part_sensors.mp3",
  partBrain: "part_brain.mp3",
  partMap: "part_map.mp3",
  partTrophy: "part_trophy.mp3",
  questLearn: "quest_learn.mp3",
  questTrain: "quest_train.mp3",
  questTest: "quest_test.mp3",
  questNavigate: "quest_navigate.mp3",
  questFinal: "quest_final.mp3",
  q1Start: "q1_start.mp3",
  q1Title: "q1_title.mp3",
  q1Instruction: "q1_instruction.mp3",
  q1Done: "q1_done.mp3",
  q1Learned: "q1_learned.mp3",
  correct: "correct.mp3",
  wrong: "wrong.mp3",
  summary: "summary.mp3",
  summaryBias: "summary_bias.mp3",
  summaryLearned: "summary_learned.mp3",
  q3Start: "q3_start.mp3",
  q3Done: "q3_done.mp3",
  q3Retrain: "q3_retrain.mp3",
  q3Learned: "q3_learned.mp3",
  q4Start: "q4_start.mp3",
  q4Correct: "q4_correct.mp3",
  q4Wrong: "q4_wrong.mp3",
  q4AiRight: "q4_ai_right.mp3",
  q4Done: "q4_done.mp3",
  q4Learned: "q4_learned.mp3",
  q5Start: "q5_start.mp3",
  q5Done: "q5_done.mp3",
  q5Learned: "q5_learned.mp3",
  allDone: "all_done.mp3",
};
